#!/bin/sh

# Get all files staged for commit
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$")

# If no files are found then exit
if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

# Succesfully commits if true
PASS=true

echo "Validating Commit:"

# Ensure the user has PHPCS installed
which ./vendor/bin/phpcs &> /dev/null
if [[ "$?" == 1 ]]; then
  echo "Please install PHPCS"
  exit 1
fi

# Ensure the user has PHPCBF installed
which ./vendor/bin/phpcbf &> /dev/null
if [[ "$?" == 1 ]]; then
  echo "Please install PHPCBF"
  exit 1
fi

# Ensure the user has PHPUNIT installed
which ./vendor/bin/phpunit &> /dev/null
if [[ "$?" == 1 ]]; then
  echo "Please install PHPUNIT"
  exit 1
fi

# Ensure the user has PHPDOX installed
which ./vendor/bin/phpdox &> /dev/null
if [[ "$?" == 1 ]]; then
  echo "Please install PHPDOX"
  exit 1
fi

# Run the build script
echo "building application"
composer build

if [[ "$?" == 0 ]]; then
  echo "Building succeeded"
else
  echo "Building failed"
  PASS=false
fi

echo "Commit validation completed!"

if ! $PASS; then
  echo "COMMIT FAILED: There were errors with your commit. Please fix them and try again."
  exit 1
else
  echo "COMMIT SUCCEEDED"
fi

exit $?
